name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Java 环境（JDK 1.8）
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # 使用 Zulu OpenJDK
          java-version: '8'     # 指定 JDK 1.8

      # 3. 缓存 Gradle 依赖
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. 构建 APK
      - name: Build APK
        run: bash ./gradlew assembleRelease

      # 5. 上传构建产物
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: app/build/outputs/apk/release/*.apk
